---
stages:
- build

variables:
  DOCKER_HUB_IMAGE: "${DOCKER_HUB_USERNAME}/${CI_PROJECT_NAME}"

kaniko:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
  - mkdir --parents /kaniko/.docker
  - export IMAGE_VERSION="$(date +%Y%m%dT%H%M%S)"
  - |
    echo "{
      \"auths\": {
        \"${CI_REGISTRY}\": {
          \"username\": \"${CI_REGISTRY_USER}\",
          \"password\":\"${CI_REGISTRY_PASSWORD}\"
        },
        \"${DOCKER_HUB_URL}\": {
          \"username\": \"${DOCKER_HUB_USERNAME}\",
          \"password\":\"${DOCKER_HUB_PASSWORD}\"
        }
      }
    }" > /kaniko/.docker/config.json
  - /kaniko/executor --context="${CI_PROJECT_DIR}" --destination="${CI_REGISTRY_IMAGE}:${IMAGE_VERSION}" --destination="${DOCKER_HUB_IMAGE}:${IMAGE_VERSION}" --dockerfile="${CI_PROJECT_DIR}/Dockerfile"
  - echo "Successfully publised new image ${CI_REGISTRY_IMAGE}:${IMAGE_VERSION}"
  - echo "Successfully publised new image ${DOCKER_HUB_IMAGE}:${IMAGE_VERSION}"
  stage: build
  tags:
  - kubernetes
